### ISSUE TITLE
historyScore assertion failed in certain forced mate positions

### ISSUE THREAD

**Issue by En-En-Code** [casanche/casanchess#1]
In positions with few pieces and a forced mate, Casanchess sometimes goes to very high depths, which in itself is not a problem. However, doing this causes the following assert to fail:
```
casanchess: /file-path/casanchess/src/Heuristics.cpp:108: void {anonymous}::RateMoves(Board&, MoveList&, TT&, const Heuristics&, int): Assertion `historyScore >= minScore && historyScore <= maxScore' failed.
```
With a little testing, `historyScore` fails the first half of the assert by being negative, either due to overflow or some other oversight.
Here are a couple of positions this triggers in, both of which occurred in test 1 min + 1 sec games (these also fail the assert with `go depth 70`, although it triggers at earlier depths than that).
* +M9 for side to move: `8/3B2k1/6P1/5PK1/1p6/1P5p/8/8 w - - 0 49`
* -M6 for side to move: `8/8/6k1/r7/3p4/6K1/8/1q6 w - - 0 102`

**Comment by casanche** [comment]
Good catch @En-En-Code !
I was able to reproduce the bug in both positions.

The issue was triggered, as you had correctly guessed, due to an overflow of `historyScore` in this line:
https://github.com/casanche/casanchess/blob/c2a8d7bcb589f2bb13753707cfd7e3daff93917b/src/Heuristics.cpp#L107-L107
The intermediate value of the operation can take values up to `179 * historyScore` before performing the division, a value that is reached way before the constant defined to reduce the history values:
https://github.com/casanche/casanchess/blob/c2a8d7bcb589f2bb13753707cfd7e3daff93917b/include/Heuristics.h#L11-L11

Setting the constant to a lower value like `INFINITE / 512` solves the issue. In addition, modify the reduction when that value is reached from `/= 4` to `/= 16` helps to trigger less often the maximum value in such extreme cases.

It is very rare to reach this value in a regular game (since there is history aging between moves), so only could be observed in mate positions, where Casanchess go to such high depths as you noticed. I agree that this behavior is not ideal, but meanwhile, this patch should solve the assertion errors at any depth. At least this helped to debug errors at very high depths :sweat_smile:

Thanks for contributing to the project!
